### ISSUE TITLE
FPSim2CudaEngine TypeError: missing positional argument: 'pg_schema'

### ISSUE THREAD

**Issue by seanryanchan** [chembl/FPSim2#97]
FPSim2CudaEngine raises an error immediately. See the code below (in interactive Python)
```
>>> from FPSim2 import FPSim2CudaEngine
>>> fpe = FPSim2CudaEngine(H5DB_FILENAME)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/fpsim2/lib/python3.9/site-packages/FPSim2/FPSim2Cuda.py", line 99, in __init__
    super(FPSim2CudaEngine, self).__init__(
TypeError: __init__() missing 1 required positional argument: 'pg_schema'
```

**Comment by eloyfelix** [comment]
thanks for reporting. I don't have a great way of testing the Cuda engine. PR on its way https://github.com/chembl/FPSim2/pull/98  and new version (0.4.5) to be released today.
